Algoritmo "Variáveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/03/2022
Var
// Seção de Declarações das variáveis
primeiroNome, segundoNome, cidade, endereco: caractere
idade: inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo